development:
  sessions:
    default:
      database: machine_learning_development
      hosts:
        - xiongdl2009.vicp.cc:16097
      options:
  options:
production:
  sessions:
    default:
      database: machine_learning_development
      hosts:
        - xiongdl2009.vicp.cc:16097
      options:
  options:
test:
  sessions:
    default:
      database: machine_learning_test
      hosts:
        - xiongdl2009.vicp.cc:16097
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
