development:
  sessions:
    default:
      database: machine_learning_development
      hosts:
        - 127.0.0.1:27018
      options:
  options:
production:
  sessions:
    default:
      database: machine_learning_development
      hosts:
        - 127.0.0.1:27018
      options:
  options:
test:
  sessions:
    default:
      database: machine_learning_test
      hosts:
        - 127.0.0.1:27018
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
